---
openapi: 3.0.0
info:
  title: Tracer
  description: API que permite gestionar el servicio de rastreo de los paquetes de los usuarios de la tienda virtual
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: SwaggerHub API Auto Mocking
security:
  - application:
      - read
      - write
paths:
  /pedidos/{id_pedido}/addEstado:
    patch:
      summary: Permite asignar estado a un pedido
      description: Esta operación permite agregar un estado a un pedido dado su id y el estado que se desea agregar
      parameters:
        - name: id_pedido
          in: path
          description: ID del pedido a actualizar
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/id_pedido_estado_body'
        required: true
      responses:
        "200":
          description: OK
  /pedidos/{id_pedido}/tracer:
    get:
      summary: Permite rastrear de un pedido dado su ID
      description: Esta operación permite obtener los atributos relacionados a un pedido dado su identificador
      parameters:
        - name: id
          in: path
          description: ID del pedido a buscar
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pedido'
  /pedidos/{id_pedido}:
    get:
      summary: Permite buscar un pedido dado su ID
      description: This is an example operation to show how security is applied to the call.
      parameters:
        - name: id
          in: path
          description: ID del pedido a buscar
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: Authorization
          in: header
          description: Token de autorización del usuario
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pedido'
  /pedidos/{id_pedido}/time:
    get:
      summary: Permite obtener la fecha estimada de entrega de un pedido
      description: Esta operación permite estimar la fecha de entrega de un producto dado su id
      parameters:
        - name: id_pedido
          in: path
          description: ID del pedido
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: OK
  /pedidos/{id_pedido}/transportadoras:
    get:
      summary: Permite obtener la información de la transportadora encargada de entregar el pedido
      description: This is an example operation to show how security is applied to the call.
      parameters:
        - name: id_pedido
          in: path
          description: ID del pedido a consultar
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: OK
  /pedidos/{id_pedido}/datetime_adjust:
    get:
      summary: Permite ajustar la zona horaria
      description: This is an example operation to show how security is applied to the call.
      parameters:
        - name: id_pedido
          in: path
          description: ID del pedido al cual se le ajustará la zona horaria
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: OK
  /tokens/generacion:
    post:
      summary: Genera un token de autenticación
      description: Permite generar un token de autenticación para un usuario dado
      parameters:
        - name: subject
          in: query
          description: Nombre del usuario para el cual se generará el token
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
  /tokens/validacion:
    get:
      summary: Valida un token de autenticación
      description: Permite validar un token de autenticación para un usuario dado
      parameters:
        - name: tokenString
          in: query
          description: Token de autenticación a validar
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: correo
          in: query
          description: correo electronico del usuario que quiere validar su token
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: boolean
  /tokens/sujeto:
    get:
      summary: Obtiene el nombre del usuario asociado a un token de autenticación
      description: Permite obtener el nombre del usuario asociado a un token de autenticación
      parameters:
        - name: tokenString
          in: query
          description: Token de autenticación del cual se desea conocer el nombre del usuario
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    id_pedido_estado_body:
      type: object
      properties:
        estado_envio:
          type: string
          example: entregado
    Pedido:
      type: object
      properties:
        id:
          type: string
        estado_envio:
          type: object
        fecha_envio:
          type: string
        fecha_entrega:
          type: string
        ubicaciones:
          type: array
          items:
            type: object
            properties:
              latitud:
                type: number
              longitud:
                type: number
        transportadora:
          type: object
          properties:
            nombre:
              type: string
            direccion:
              type: string
            telefono:
              type: string
    Usuario:
      type: object
      properties:
        id:
          type: string
        nombre:
          type: string
        apellido:
          type: string
        correo:
          type: string
        credential:
          type: object
          properties:
            id:
              type: string
            username:
              type: string
            password:
              type: string
            rol:
              type: string
              enum:
                - EMPLEADO
                - ADMINISTRADOR
                - USUARIO
              description: Rol del usuario




